#!/usr/bin/env python3
"""Prepare the image assets for this meetup deck from the files in Sources/.

Re-runnable: everything under assets/ (except qr/, generated by the builder) is
derived from Sources/<meetup>/ and the previous deck, so it can be regenerated.
"""
from pathlib import Path
import zipfile, io
from PIL import Image, ImageDraw

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent.parent
SRC = ROOT / "Sources" / HERE.name
A = HERE / "assets"
for d in ("logos", "photos", "icons"):
    (A / d).mkdir(parents=True, exist_ok=True)


def whiten_to_alpha(im, thresh=235):
    """Turn a light background (white/near-white/light grey) transparent."""
    im = im.convert("RGBA")
    px = im.load()
    w, h = im.size
    for y in range(h):
        for x in range(w):
            r, g, b, a = px[x, y]
            if r > thresh and g > thresh and b > thresh:
                px[x, y] = (r, g, b, 0)
    return im


def trim(im, pad=0):
    bbox = im.getchannel("A").getbbox() if im.mode == "RGBA" else im.getbbox()
    if not bbox:
        return im
    l, t, r, b = bbox
    return im.crop((max(0, l - pad), max(0, t - pad), min(im.width, r + pad), min(im.height, b + pad)))


# --- Sponsor / partner logos -------------------------------------------------
syn = Image.open(SRC / "logos" / "Synvert_xgeeks_main (1) copy 2.png").convert("RGBA")
trim(syn).save(A / "logos" / "synvert-xgeeks.png")

va = Image.open(SRC / "logos" / "WhatsApp Image 2026-08-20 at 11.02.23 (1).jpeg")
va = trim(whiten_to_alpha(va, 225), pad=20)
va.save(A / "logos" / "va-coworking.png")

osug = Image.open(SRC / "logos" / "Screenshot 2026-09-08 at 10.24.45.png").convert("RGBA")
# small screenshot: crop the light border, upscale 3x for smoother edges
osug = osug.resize((osug.width * 3, osug.height * 3), Image.LANCZOS)
osug = trim(whiten_to_alpha(osug, 225), pad=10)
osug.save(A / "logos" / "outsystems-user-groups.png")

# --- Community logo + social icons from the previous deck ----------------------
prev = zipfile.ZipFile(SRC / "previous-deck" / "#4 AWS UG Porto - Presentation.pptx")
def media(name):
    return Image.open(io.BytesIO(prev.read(f"ppt/media/{name}")))
media("image15.jpg").convert("RGB").save(A / "logos" / "aws-ug-porto.jpg", quality=92)
media("image5.png").save(A / "icons" / "slack.png")
media("image11.png").save(A / "icons" / "meetup.png")
media("image19.png").save(A / "icons" / "linkedin.png")
media("image7.jpg").convert("RGB").save(A / "icons" / "microphone.jpg", quality=92)

# --- KCD lockup (KCD Porto + DevOpsDays Portugal) from a keynote card ---------
key = sorted((SRC / "kcd-keynotes").glob("*.jpeg"))
k0 = Image.open(key[0]).convert("RGB")
k0.crop((60, 52, 366, 210)).save(A / "logos" / "kcd-porto-devopsdays.jpg", quality=95)

# --- Keynote portraits (right panel of each card) ------------------------------
# (file, name) -> the crop box was checked visually
keynotes = {
    "1785754017283.jpeg": ("manuel-pais", (600, 120, 1015, 660)),
    "1786110193096.jpeg": ("juraci-paixao", (600, 90, 1015, 630)),
    "1786964541481.jpeg": ("mario-fahlandt", (600, 80, 1015, 620)),
    "1787562621817.jpeg": ("natanael-copa", (600, 120, 1015, 660)),
}
for fn, (slug, box) in keynotes.items():
    im = Image.open(SRC / "kcd-keynotes" / fn).convert("RGB").crop(box)
    im.save(A / "photos" / f"{slug}.jpg", quality=92)

# --- Today's speakers, cropped from the #8 event banner (meetup.com) ----------
ban = Image.open(SRC / "banner" / "meetup-event-featured-photo (#8 banner from meetup.com).jpeg").convert("RGB")
ban.crop((1192, 236, 1663, 726)).save(A / "photos" / "ricardo-pereira.jpg", quality=92)
ban.crop((1192, 918, 1663, 1408)).save(A / "photos" / "rafael-arruda.jpg", quality=92)

# --- Background: banner gradient (navy -> purple) + the previous deck's diagonal bands
W, H = 2560, 1440
NAVY, PURPLE = (0x20, 0x1E, 0x37), (0x7B, 0x5A, 0xC2)
bg = Image.new("RGB", (W, H))
px = bg.load()
for y in range(H):
    for x in range(W):
        t = (x / W) * 0.78 + (y / H) * 0.22          # direction: mostly left->right, a bit downwards
        t = min(1.0, max(0.0, (t - 0.02) / 0.50))     # purple fully reached ~52% across (as in banner)
        t = t * t * (3 - 2 * t)                       # smoothstep
        px[x, y] = tuple(int(NAVY[i] + (PURPLE[i] - NAVY[i]) * t) for i in range(3))
# diagonal bands (previous deck motif), subtle
ov = Image.new("RGBA", (W, H), (0, 0, 0, 0))
d = ImageDraw.Draw(ov)
for x0, wdt, col in ((int(W * 0.46), int(W * 0.22), (255, 255, 255, 14)),
                     (int(W * 0.70), int(W * 0.18), (0, 0, 0, 26)),
                     (int(W * 0.90), int(W * 0.30), (255, 255, 255, 12))):
    d.polygon([(x0, H), (x0 + wdt, H), (x0 + wdt + int(H * 0.55), 0), (x0 + int(H * 0.55), 0)], fill=col)
bg = Image.alpha_composite(bg.convert("RGBA"), ov).convert("RGB")
bg.save(A / "background.jpg", quality=93, subsampling=0)
print("assets ready:", sorted(p.relative_to(A).as_posix() for p in A.rglob("*") if p.is_file()))
